# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""EnergyShareRequirements

    EnergyShareRequirements(;
        name=nothing,
        id=nothing,
        available=nothing,
        eligible_regions=nothing,
        generation_fraction=1e8,
    )

    - name::String
    - id::Int64
    - available::Bool
    - eligible_regions::Vector{Int64}
    - generation_fraction::Float64
"""
Base.@kwdef mutable struct EnergyShareRequirements <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    available::Union{Nothing, Bool} = nothing
    eligible_regions::Union{Nothing, Vector{Int64}} = nothing
    generation_fraction::Union{Nothing, Float64} = 1e8

    function EnergyShareRequirements(
        name,
        id,
        available,
        eligible_regions,
        generation_fraction,
    )
        OpenAPI.validate_property(EnergyShareRequirements, Symbol("name"), name)
        OpenAPI.validate_property(EnergyShareRequirements, Symbol("id"), id)
        OpenAPI.validate_property(EnergyShareRequirements, Symbol("available"), available)
        OpenAPI.validate_property(
            EnergyShareRequirements,
            Symbol("eligible_regions"),
            eligible_regions,
        )
        OpenAPI.validate_property(
            EnergyShareRequirements,
            Symbol("generation_fraction"),
            generation_fraction,
        )
        return new(name, id, available, eligible_regions, generation_fraction)
    end
end # type EnergyShareRequirements

const _property_types_EnergyShareRequirements = Dict{Symbol, String}(
    Symbol("name") => "String",
    Symbol("id") => "Int64",
    Symbol("available") => "Bool",
    Symbol("eligible_regions") => "Vector{Int64}",
    Symbol("generation_fraction") => "Float64",
)
OpenAPI.property_type(::Type{EnergyShareRequirements}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_EnergyShareRequirements[name]))}

function check_required(o::EnergyShareRequirements)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{EnergyShareRequirements}, name::Symbol, val) end
