# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CurtailableDemandSideTechnology

    CurtailableDemandSideTechnology(;
        name=nothing,
        id=nothing,
        available=nothing,
        power_systems_type=nothing,
        region=nothing,
        curtailment_cost=nothing,
        max_demand_curtailment=nothing,
        min_power=nothing,
    )

    - name::String
    - id::Int64
    - available::Bool
    - power_systems_type::String
    - region::Vector{Int64}
    - curtailment_cost::Dict{String, ValueCurve}
    - max_demand_curtailment::Float64
    - min_power::Float64
"""
Base.@kwdef mutable struct CurtailableDemandSideTechnology <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    available::Union{Nothing, Bool} = nothing
    power_systems_type::Union{Nothing, String} = nothing
    region::Union{Nothing, Vector{Int64}} = nothing
    curtailment_cost::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, ValueCurve} }
    max_demand_curtailment::Union{Nothing, Float64} = nothing
    min_power::Union{Nothing, Float64} = nothing

    function CurtailableDemandSideTechnology(name, id, available, power_systems_type, region, curtailment_cost, max_demand_curtailment, min_power, )
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("name"), name)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("id"), id)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("available"), available)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("power_systems_type"), power_systems_type)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("region"), region)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("curtailment_cost"), curtailment_cost)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("max_demand_curtailment"), max_demand_curtailment)
        OpenAPI.validate_property(CurtailableDemandSideTechnology, Symbol("min_power"), min_power)
        return new(name, id, available, power_systems_type, region, curtailment_cost, max_demand_curtailment, min_power, )
    end
end # type CurtailableDemandSideTechnology

const _property_types_CurtailableDemandSideTechnology = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("id")=>"Int64", Symbol("available")=>"Bool", Symbol("power_systems_type")=>"String", Symbol("region")=>"Vector{Int64}", Symbol("curtailment_cost")=>"Dict{String, ValueCurve}", Symbol("max_demand_curtailment")=>"Float64", Symbol("min_power")=>"Float64", )
OpenAPI.property_type(::Type{ CurtailableDemandSideTechnology }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CurtailableDemandSideTechnology[name]))}

function check_required(o::CurtailableDemandSideTechnology)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.power_systems_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CurtailableDemandSideTechnology }, name::Symbol, val)








end
