# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MinimumCapacityRequirements

    MinimumCapacityRequirements(;
        name=nothing,
        id=nothing,
        available=nothing,
        eligible_resources=nothing,
        min_capacity_mw=nothing,
    )

    - name::String
    - id::Int64
    - available::Bool
    - eligible_resources::Vector{Int64}
    - min_capacity_mw::Float64
"""
Base.@kwdef mutable struct MinimumCapacityRequirements <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing
    available::Union{Nothing, Bool} = nothing
    eligible_resources::Union{Nothing, Vector{Int64}} = nothing
    min_capacity_mw::Union{Nothing, Float64} = nothing

    function MinimumCapacityRequirements(name, id, available, eligible_resources, min_capacity_mw, )
        OpenAPI.validate_property(MinimumCapacityRequirements, Symbol("name"), name)
        OpenAPI.validate_property(MinimumCapacityRequirements, Symbol("id"), id)
        OpenAPI.validate_property(MinimumCapacityRequirements, Symbol("available"), available)
        OpenAPI.validate_property(MinimumCapacityRequirements, Symbol("eligible_resources"), eligible_resources)
        OpenAPI.validate_property(MinimumCapacityRequirements, Symbol("min_capacity_mw"), min_capacity_mw)
        return new(name, id, available, eligible_resources, min_capacity_mw, )
    end
end # type MinimumCapacityRequirements

const _property_types_MinimumCapacityRequirements = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("id")=>"Int64", Symbol("available")=>"Bool", Symbol("eligible_resources")=>"Vector{Int64}", Symbol("min_capacity_mw")=>"Float64", )
OpenAPI.property_type(::Type{ MinimumCapacityRequirements }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MinimumCapacityRequirements[name]))}

function check_required(o::MinimumCapacityRequirements)
    o.name === nothing && (return false)
    o.available === nothing && (return false)
    o.eligible_resources === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ MinimumCapacityRequirements }, name::Symbol, val)





end
