# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""FuelCurve_fuel_cost

    FuelCurveFuelCost(; value=nothing)
"""
mutable struct FuelCurveFuelCost <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Float64, String }
    FuelCurveFuelCost() = new()
    FuelCurveFuelCost(value) = new(value)
end # type FuelCurveFuelCost

function OpenAPI.property_type(::Type{ FuelCurveFuelCost }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(FuelCurveFuelCost, name)
end
