name = "PowerSystemsInvestmentsPortfolios"
uuid = "9212B679-331E-471F-8FA8-FF293E16DBC8"
authors = ["Jose Daniel Lara", "Sourabh Dalvi"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
DocStringExtensions = "~0.9"
julia = "^1.6"
